[project]
name = "mlflow-3-tutorials"
version = "0.1.0"
description = "Tutorials for MLflow 3"
readme = "README.md"
authors = [
    { name = "Laurens van der Tas", email = "laurens.vandertas@gmail.com" },
]
requires-python = ">=3.12"
dependencies = [
    "hyperopt>=0.2.7",
    "loguru>=0.7.3",
    "mlflow[extras]>=3.1.1",
    "numpy>=2.1.3",
    "pandas>=2.3.0",
    "scikit-learn>=1.7.0",
    "tensorflow>=2.19.0",
]

[project.scripts]
run_sync = "mlflow_3_tutorials.lib.scripts:uv_sync"
run_server = "mlflow_3_tutorials.lib.scripts:start_tracking_server"
run_precommit = "mlflow_3_tutorials.lib.scripts:run_precommit"
run_pyment = "mlflow_3_tutorials.lib.scripts:run_pyment"
first_model = "mlflow_3_tutorials.first_model:main"

[dependency-groups]
dev = [
    "basedpyright>=1.29.4",
    "ipykernel>=6.29.5",
    "ipywidgets>=8.1.7",
    "mccabe>=0.7.0",
    "pre-commit>=4.2.0",
    "pyment>=0.3.3",
]
test = [
    "pytest>=8.4.1",
    "pytest-sugar>=1.0.0",
]

[build-system]
requires = [
    "hatchling",
]
build-backend = "hatchling.build"
