[project]
name = "mlflow-3-tutorials"
version = "0.1.0"
description = "Tutorials for MLflow 3"
readme = "README.md"
authors = [
    { name = "Laurens van der Tas", email = "laurens.vandertas@gmail.com" },
]
requires-python = ">=3.12"
dependencies = [
    "loguru>=0.7.3",
    "mlflow>=3.1.1",
    "scikit-learn>=1.7.0",
]

[project.scripts]
sync = "mlflow_3_tutorials.lib.scripts:uv_sync"
server = "mlflow_3_tutorials.lib.scripts:start_tracking_server"
first_model = "mlflow_3_tutorials.first_model:main"

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
    "ipywidgets>=8.1.7",
    "mccabe>=0.7.0",
    "pre-commit>=4.2.0",
]
test = [
    "pytest>=8.4.1",
    "pytest-sugar>=1.0.0",
]

[build-system]
requires = [
    "hatchling",
]
build-backend = "hatchling.build"
