# This file defines tasks for managing the MLflow 3 Tutorials project.

version: '3'

env:
  MLFLOW_DOWNLOAD_CHUNK_TIMEOUT: 5
  MLFLOW_ARTIFACT_UPLOAD_DOWNLOAD_TIMEOUT: 5

vars:
  PY:
    sh: |
      if command -v uv >/dev/null 2>&1; then
        echo "uv run"
      else
        echo "python -m"
      fi
  HOST: 127.0.0.1
  PORT: 5000

tasks:
  default:
    cmd: task --list
    silent: true

  # Repository management commands
  repo:sync:
    desc: Install all dependencies
    aliases: [sync]
    cmd: '{{.PY}} run_sync'

  repo:pre-commit:
    desc: Run pre-commit hooks
    aliases: [pc]
    cmd: '{{.PY}} run_precommit'

  repo:format-docs:
    desc: Format all docstrings with Pyment
    aliases: [fmt]
    cmd: '{{.PY}} run_pyment'

  # Tests commands
  test:coverage:
    desc: Run tests with coverage and generate HTML report
    aliases: [cov]
    cmd: pytest --cov --cov-report=html

  # MLflow commands
  mlflow:stop-server:
    desc: Stop local MLflow tracking server
    aliases: [stop]
    cmd: |
      pid=$(pgrep -f mlflow.server:app)
      if [ -n "$pid" ]; then
        kill $pid
      fi

  mlflow:start-server:
    desc: Launch local MLflow tracking server
    aliases: [mlflow]
    cmd: '{{.PY}} start_server'

  mlflow:remove-experiments:
    desc: Delete all MLflow experiments except 0 (-- -a/--all removes mlflow/)
    aliases: [rmx]
    cmd: '{{.PY}} remove_experiments {{.CLI_ARGS}}'

  mlflow:serve-wine:
    desc: Serve the Wine model
    vars: {VERSION: 1, SERVE_PORT: 5002}
    aliases: [serve]
    cmd: '{{.PY}} serve_wine_model --version={{.VERSION}} --port={{.SERVE_PORT}}'

  # Project tutorials
  proj:first-model:
    desc: Run first-model notebook pipeline
    aliases: [fm]
    cmd: '{{.PY}} first_model'

  proj:tuning:
    desc: Hyper-parameter tuning + deployment
    aliases: [td]
    cmd: '{{.PY}} tuning_deployment'

  proj:deep-learning:
    desc: Quick-start deep-learning example
    aliases: [dl]
    cmd: '{{.PY}} deep_learning'

  proj:model-registry:
    desc: Quick-start model-registry example
    aliases: [mr]
    cmd: '{{.PY}} model_registry'

  proj:optuna-tuning-tracking:
    desc: Optuna hyperparameter tuning + tracking (nested) runs
    aliases: [ot]
    cmd: '{{.PY}} optuna_tuning_tracking'

  proj:logging-visualizations:
    desc: Logging and visualization of metrics
    aliases: [lv]
    cmd: '{{.PY}} logging_visualizations'
