# This file defines tasks for managing the MLflow 3 Tutorials project.

version: '3'

vars:
  PY:
    sh: |
      if command -v uv >/dev/null 2>&1; then
        echo "uv run"
      else
        echo "python -m"
      fi
  HOST: 127.0.0.1
  PORT: 5000

tasks:
  default:
    desc: List available tasks
    cmds: [task --list]
    silent: true

  # Interal commands
  int:address-free:
    desc: Check if port {{.HOST}}:{{.PORT}} is free
    aliases: [free]
    internal: true
    cmds:
      - cmd: '{{.PY}} port_free'
        silent: true

  # Repository commands
  repo:sync:
    desc: Install all dependencies (optionally extra packages)
    aliases: [sync]
    cmds: ['{{.PY}} run_sync {{.EXTRAS | default ""}}']

  repo:precommit:
    desc: Run pre-commit hooks
    aliases: [pc]
    cmds: ['{{.PY}} run_precommit']

  repo:pyment:
    desc: Format all docstrings
    aliases: [fmt]
    cmds:
      - '{{.PY}} run_pyment'

  # Test commands
  test:cov:
    desc: Run tests with coverage report
    aliases: [cov]
    cmds:
      - pytest --cov --cov-report html

  # MLflow commands
  mlflow:start-server:
    desc: Launch local MLflow tracking server
    aliases: [mlflow]
    status: [free]
    cmds: ['{{.PY}} start_server']

  mlflow:rm-experiments:
    desc: >
      Delete all MLflow experiments except 0.
      (`task rmx -- --all/-a` removes mlflow/)
    aliases: [rmx]
    cmds: ['{{.PY}} remove_experiments {{.CLI_ARGS}}']
    deps:
      - mlflow:start-server

  mlflow:serve-model:
    desc: Serve the Wine model (VERSION defaults to 1, PORT=5002)
    vars: { VERSION: 1, PORT: 5002 }
    aliases: [serve]
    cmds:
      - '{{.PY}} serve_wine_model --version={{.VERSION}} --port={{.PORT}}'
    deps:
      - mlflow:start-server

  # Project tutorials
  proj:first-model:
    desc: Run first-model notebook pipeline
    aliases: [fm]
    cmds: ['{{.PY}} first_model']
    deps:
      - mlflow:start-server

  proj:tuning:
    desc: Hyper-parameter tuning + deployment
    aliases: [td]
    cmds: ['{{.PY}} tuning_deployment']
    deps:
      - mlflow:start-server

  proj:deep-learning:
    desc: Quick-start deep-learning example
    aliases: [dl]
    cmds: ['{{.PY}} deep_learning']
    deps:
      - mlflow:start-server

  proj:model-registry:
    desc: Quick-start model-registry example
    aliases: [mr]
    cmds: ['{{.PY}} model_registry']
    deps:
      - mlflow:start-server
